<div class="columns my-2">
  <div class="column">
    <div class="empty">
      <div class="empty-icon">
        <span class="ec ec-busts-in-silhouette ec_f_lg"></span>
      </div>
      <p class="empty-title h5">Waiting for the pokers to enter the room.</p>
      <!-- <p class="empty-subtitle">Click the button to start a conversation.</p> -->
      <!-- <div class="empty-action">
        <button class="btn btn-primary">Send a message</button>
      </div> -->
    </div>
  </div>
</div>