spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:h2:mem:db_poker;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    username: poker
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: embedded
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug